<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Db;
use Neoan3\Frame\Demo;
use Neoan3\Model\DealerModel;

class Zip extends Demo
{
    function getZip(array $body)
    {
        Db::setEnvironment(['name'=>'clifford_api']);
        return DealerModel::find($body['zip']);
    }

    function postZip(array $body)
    {
        
    }

}
