<?php
/* Generated by neoan3-cli */

namespace Neoan3\Components;

use Neoan3\Apps\Curl;
use Neoan3\Core\Unicore;

class Test extends Unicore
{
    function init()
    {
        $this->uni('demo')
            ->hook('main', 'test', [
                'headline' => 'adam'
            ])
            ->callback($this, 'fire')
            ->output();
    }

    function fire()
    {
        $url = 'https://oovix5dya8.execute-api.us-east-2.amazonaws.com/DevGithub/myTestWH';
        $payload = json_decode('{
  "newState": {
    "ID": "5ebc32e70212d892c603a9e580c78ce3",
    "name": "Waiting for State of Nebraska Legal to approve our SOW",
    "objCode": "TASK",
    "assignedToID": "5e8c8cdc00c8be01d0922066704d3006",
    "entryDate": "2020-05-13T11:48:23.060-0600",
    "roleID": null,
    "accessorIDs": [
      "5e8c8cdc00c8be01d0922066704d3006",
      "a2a62bb8b0e4379ee053a7656a0ae755",
      "a2a62bb8b3c1379ee053a7656a0ae755",
      "5e8c8a4d00c5ebb78efd06ba6a7e50bc"
    ],
    "lastUpdateDate": "2020-05-20T11:41:49.012-0600",
    "description": null,
    "plannedCompletionDate": "2020-05-25T16:00:00.000-0600",
    "enteredByID": "5e8c8cdc00c8be01d0922066704d3006",
    "priority": 2,
    "referenceNumber": 6353,
    "teamID": null,
    "lastUpdatedByID": "5e8c8cdc00c8be01d0922066704d3006",
    "customerID": "a2a62bb8ace2379ee053a7656a0ae755",
    "iterationID": null,
    "projectID": "5eaad7f3006044b07c9aaa7f3f8107b2",
    "categoryID": null,
    "status": "INP",
    "parameterValues": {}
  },
  "oldState": {
    "ID": "5ebc32e70212d892c603a9e580c78ce3",
    "name": "Waiting for State of Nebraska Legal to approve our SOW",
    "objCode": "TASK",
    "assignedToID": "5e8c8cdc00c8be01d0922066704d3006",
    "entryDate": "2020-05-13T11:48:23.060-0600",
    "roleID": null,
    "accessorIDs": [
      "5e8c8cdc00c8be01d0922066704d3006",
      "a2a62bb8b0e4379ee053a7656a0ae755",
      "a2a62bb8b3c1379ee053a7656a0ae755",
      "5e8c8a4d00c5ebb78efd06ba6a7e50bc"
    ],
    "lastUpdateDate": "2020-05-13T11:48:28.604-0600",
    "description": null,
    "plannedCompletionDate": "2020-05-25T16:00:00.000-0600",
    "enteredByID": "5e8c8cdc00c8be01d0922066704d3006",
    "priority": 2,
    "referenceNumber": 6353,
    "teamID": null,
    "lastUpdatedByID": "5e8c8cdc00c8be01d0922066704d3006",
    "customerID": "a2a62bb8ace2379ee053a7656a0ae755",
    "iterationID": null,
    "projectID": "5eaad7f3006044b07c9aaa7f3f8107b2",
    "categoryID": null,
    "status": "NEW",
    "parameterValues": {}
  },
  "eventTime": {
    "epochSecond": 1589996509,
    "nano": 128924000
  },
  "subscriptionId": "47b933efe86146469003994e16613f75",
  "eventType": "UPDATE"
}');
        $d = Curl::post($url, $payload);
        var_dump($d);

    }

}
